language: r
env: _R_CHECK_CRAN_INCOMING_=FALSE
sudo: required

r:
  - release

r_packages:
  - covr
  - devtools

r_github_packages:
  - DiegoKoz/presentes

before_install: R -e 'install.packages("remotes")'

after_success:
- Rscript -e 'library(covr);codecov()'
